<?php defined( 'ABSPATH' ) || exit; ?>
<h2><?php echo esc_html( sprintf( __( 'Training Entitlements — Order #%s', 'aspen-learndash-entitlements' ), $order->get_order_number() ) ); ?></h2>
<?php foreach ( $grants as $grant ) : $state = Aspen\LearnDashEntitlements\Repository::state( $grant ); $remaining = max( 0, (int) $grant['total_count'] - (int) $grant['redeemed_count'] ); ?>
<section class="aspen-lde-grant" style="margin:1.5em 0;padding:1em;border:1px solid #ddd">
<h3><?php echo esc_html( get_the_title( $grant['course_id'] ) ); ?></h3>
<p><strong><?php esc_html_e( 'Status:', 'aspen-learndash-entitlements' ); ?></strong> <?php echo esc_html( ucfirst( $state ) ); ?><br><strong><?php esc_html_e( 'Entitlements:', 'aspen-learndash-entitlements' ); ?></strong> <?php echo esc_html( $grant['total_count'] ); ?><br><strong><?php esc_html_e( 'Remaining:', 'aspen-learndash-entitlements' ); ?></strong> <?php echo esc_html( $remaining ); ?><br><strong><?php esc_html_e( 'Expires:', 'aspen-learndash-entitlements' ); ?></strong> <?php echo $grant['expires_at'] ? esc_html( wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), strtotime( $grant['expires_at'] . ' UTC' ) ) ) : esc_html__( 'Does not expire', 'aspen-learndash-entitlements' ); ?></p>
<?php if ( 'active' === $state ) : $link = Aspen\LearnDashEntitlements\Enrollment_Controller::url( $grant['token'] ); ?><label><?php esc_html_e( 'Enrollment Link', 'aspen-learndash-entitlements' ); ?><input style="width:100%" readonly value="<?php echo esc_attr( $link ); ?>" onclick="this.select()"></label><?php elseif ( 'exhausted' === $state ) : ?><p><?php esc_html_e( 'All enrollments have been redeemed.', 'aspen-learndash-entitlements' ); ?></p><?php endif; ?>
<h4><?php esc_html_e( 'Enrolled users', 'aspen-learndash-entitlements' ); ?></h4><ul><?php foreach ( $this->repository()->redemptions( $grant['id'] ) as $redemption ) : ?><li><?php echo esc_html( $redemption['redeemer_name'] ); ?></li><?php endforeach; ?></ul>
</section><?php endforeach; ?>
